import { test, expect } from '@playwright/test';

async function start(page, query = '?e2e=1') {
  await page.goto(`/${query}`);
  await expect(page.getByTestId('start-race')).toBeVisible();
  await page.getByTestId('start-race').click();
  await expect(page.getByTestId('hud-lap')).toBeVisible();
}

test('ordered checkpoints accept last-checkpoint overshoot and finish exactly three laps', async ({ page }) => {
  const errors = []; page.on('pageerror', error => errors.push(error.message)); await start(page);
  const report = await page.evaluate(() => { const api = window.__APEX_DRIFT_3D_E2E__; const early = api.placeVehicleAtFinishGate({ mode: 'early' }); const partial = api.advanceCheckpointShortcut({ count: 3 }); const earlyAfterPartial = api.placeVehicleAtFinishGate({ mode: 'early' }); const laps = [api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' }), api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' }), api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' })]; return { early, partial, earlyAfterPartial, laps, final: api.snapshot() }; });
  expect(report.early.crossedFinish).toBe(false); expect(report.early.after.nextCheckpoint).toBe(report.early.before.nextCheckpoint);
  expect(report.earlyAfterPartial.crossedFinish).toBe(false); expect(report.earlyAfterPartial.after.nextCheckpoint).toBe(report.earlyAfterPartial.before.nextCheckpoint);
  expect(report.laps.map(x => x.crossedFinish)).toEqual([true, true, true]); expect(report.laps.map(x => x.lapChanged)).toEqual([true, true, false]);
  expect(report.laps.map(x => [x.before.lap, x.after.lap])).toEqual([[1, 2], [2, 3], [3, 3]]); expect(report.final.raceState).toBe('FINISHED'); expect(report.final.lap).toBe(3); expect(report.final.cameraMode).toBe('first-person'); expect(errors).toEqual([]);
});

test('checkpoint shortcut uses the shared ordered transition', async ({ page }) => { await start(page); const report = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.advanceCheckpointShortcut({ count: 12 })); expect(report.checkpointsAdvanced).toBe(12); expect(report.lapChanged).toBe(true); expect(report.after.lap).toBe(2); expect(report.after.nextCheckpoint).toBe(0); });

test('runtime driving exposes the shared physics transition result', async ({ page }) => { await start(page); await page.waitForFunction(() => window.__APEX_DRIFT_3D_E2E__.snapshot().raceState === 'RACING'); await page.keyboard.down('ArrowUp'); await page.waitForFunction(() => { const step = window.__APEX_DRIFT_3D_E2E__.snapshot().runtimePhysicsStep; return step && step.speed > 0 && Number.isFinite(step.speed) && Number.isFinite(step.slip) && Number.isFinite(step.yaw); }); const runtime = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.snapshot().runtimePhysicsStep); await page.keyboard.up('ArrowUp'); expect(runtime).toEqual(expect.objectContaining({ speed: expect.any(Number), slip: expect.any(Number), yaw: expect.any(Number) })); expect(Number.isFinite(runtime.speed) && Number.isFinite(runtime.slip) && Number.isFinite(runtime.yaw)).toBe(true); });

test('all cars, tracks, hazards, recovery timestamps, and stepped telemetry are deterministic', async ({ page }) => {
  await start(page); const report = await page.evaluate(() => { const api = window.__APEX_DRIFT_3D_E2E__; const hazards = ['neon-harbor', 'dust-canyon', 'frost-ridge'].map(trackId => ({ inside: api.enterHazardFixture({ trackId, s: .3 }), outside: api.enterHazardFixture({ trackId, s: .2 }) })); const recoveries = ['vector-gt', 'pulse-rally'].map(selectedCarId => api.induceVehicleRecovery({ selectedCarId })); return { snapshot: api.snapshot(), hazards, recoveries, runtimeRecovery: api.snapshot().vehicleRecovery, telemetry: ['vector-gt', 'comet-rs', 'pulse-rally', 'torque-v8'].map(selectedCarId => api.runCarTelemetryFixture({ selectedCarId, baselineCarId: 'vector-gt' })) }; });
  expect(report.snapshot.contentCounts).toMatchObject({ cars: 4, tracks: 3, ai: 5, totalVehicles: 6 }); expect(report.hazards.map(x => x.inside.effect.type)).toEqual(['wet', 'sand', 'ice']); expect(report.hazards.every(x => x.outside.effect.type === 'normal')).toBe(true);
  for (const recovery of report.recoveries) { expect(recovery.fixtureId).toBe('recovery-v1'); expect(recovery.seed).toBe('car-threshold-v1'); expect(recovery.trackId).toBe('neon-harbor'); expect(recovery.selected.startedAtMs).toBe(1000); expect(recovery.selected.recoveredAtMs).toBe(1000 + recovery.selected.durationMs); expect(recovery.selected.timeoutAtMs).toBe(9000); expect(recovery.selected.state).toBe('recovered'); expect(recovery.selected.lateralOffsetMeters).toBe(24); expect(recovery.selected.stallDurationMs).toBe(1000); expect(recovery.selected.timeout.timeoutAtMs).toBe(9000); expect(recovery.selected.timeout.state).toBe('timeout'); }
  expect(report.recoveries[1].comparison.ratio).toBeLessThanOrEqual(.9); expect(report.runtimeRecovery.state).toBe('recovered'); expect(report.runtimeRecovery.lateralOffsetMeters).toBe(24);
  for (const telemetry of report.telemetry) { expect(telemetry.samples).toHaveLength(50); expect(telemetry.sampleIntervalMs).toBe(100); expect(telemetry.windowMs).toBe(5000); expect(telemetry.transitionSource).toBe('production-vehicle-physics'); expect(telemetry.terminalSpeed).toBe(telemetry.samples.at(-1).speed); expect(telemetry.samples.every(x => Number.isFinite(x.speed) && Number.isFinite(x.slip) && Number.isFinite(x.yaw))).toBe(true); }
});

test('fixed slalom telemetry uses the accepted throttle and alternating steer script', async ({ page }) => { await start(page); const report = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.runCarTelemetryFixture({ fixtureId: 'fixed-slalom-v1' })); expect(report.windowMs).toBe(5000); expect(report.comparison.throttle).toBe(.75); expect(report.comparison.steerScript).toBe('alternating'); expect(report.comparison.steerMagnitude).toBe(.65); expect(report.comparison.steerSegmentMs).toBe(500); expect(report.comparison.handbrake).toBe(false); expect(report.comparison.drift).toBe(false); expect(report.samples.slice(0, 5).every(x => x.throttle === .75 && x.steer === .65 && x.handbrake === false && x.drift === false)).toBe(true); expect(report.samples.slice(5, 10).every(x => x.steer === -.65)).toBe(true); expect(report.samples.slice(10, 15).every(x => x.steer === .65)).toBe(true); });

test('AI exposes seeded ordered progress, real tolerance ratios, recovery, and order crossings', async ({ page }) => { await start(page); const report = await page.evaluate(() => { const api = window.__APEX_DRIFT_3D_E2E__; const recovery = api.induceAiRecovery({ aiId: 'ai-01' }); return { recovery, snapshot: api.snapshot() }; }); const ai = report.snapshot.aiTelemetryReport.ai; expect(ai).toHaveLength(5); expect(report.snapshot.vehicleProgress).toHaveLength(6); expect(report.snapshot.vehicleProgress.slice(1).every(x => x.kind === 'ai' && Array.isArray(x.checkpointIds) && x.trackHalfWidth === 12 && typeof x.lapIndex === 'number' && typeof x.finished === 'boolean')).toBe(true); expect(ai.every(x => x.trackHalfWidth === 12 && x.inToleranceCount <= x.lateralOffsetMetersSamples.length && x.inToleranceRatio >= 0 && x.inToleranceRatio <= 1 && x.normalizedRaceProgress >= 0)).toBe(true); expect(report.recovery.recoveryState).toBe('recovered'); expect(report.recovery.after.aiTelemetryReport.ai[0].lateralOffsetMetersSamples.some(x => Math.abs(x) > 12)).toBe(true); expect(typeof report.snapshot.aiTelemetryReport.overtakeCount).toBe('number'); });

test('live camera mount and measured frames survive COUNTDOWN, RACING, and FINISHED', async ({ page }) => { await start(page); const countdown = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.snapshot()); await page.waitForTimeout(3200); const racing = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.snapshot()); await page.evaluate(() => { const api = window.__APEX_DRIFT_3D_E2E__; api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' }); api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' }); api.placeVehicleAtFinishGate({ mode: 'afterOrderedCheckpoints' }); }); const finished = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.snapshot()); await page.waitForTimeout(100); const afterFinished = await page.evaluate(() => window.__APEX_DRIFT_3D_E2E__.snapshot()); expect(countdown.cameraMode).toBe('first-person'); expect(racing.raceState).toBe('RACING'); expect(racing.cameraMountTarget).toBe('player-cockpit'); expect(finished.raceState).toBe('FINISHED'); expect(finished.cameraMode).toBe('first-person'); expect(finished.cameraMountTarget).toBe('player-cockpit'); expect(afterFinished.performanceStats.frameCount).toBeGreaterThan(finished.performanceStats.frameCount); expect(afterFinished.performanceStats.fpsAverage).toBeGreaterThan(0); expect(afterFinished.performanceStats.maxFrameTimeMs).toBeGreaterThanOrEqual(afterFinished.performanceStats.frameTimeP95Ms); });

test('malformed and extra e2e queries are isolated and teardown is repeatable', async ({ page }) => { for (const query of ['?e2e=1x', '?e2e=1&extra=1', '?extra=1&e2e=1', '?e2e=1&e2e=1']) { await page.goto(`/${query}`); await expect(page.getByTestId('start-race')).toBeVisible(); expect(await page.evaluate(() => '__APEX_DRIFT_3D_E2E__' in window)).toBe(false); } await start(page); await expect(page.locator('canvas')).toHaveCount(1); await page.keyboard.press('M'); await expect(page.locator('canvas')).toHaveCount(0); await page.getByTestId('start-race').click(); await expect(page.locator('canvas')).toHaveCount(1); await page.keyboard.press('r'); await expect(page.locator('canvas')).toHaveCount(1); await page.keyboard.press('M'); await expect(page.locator('canvas')).toHaveCount(0); });

test('import and renderer failures show fallback without page errors', async ({ page }) => { const errors = []; page.on('pageerror', error => errors.push(error.message)); await page.route('**/vendor/three.module.min.js', route => route.abort()); await page.goto('/?e2e=1'); await expect(page.getByTestId('webgl-fallback')).toBeVisible(); expect(errors).toEqual([]); const rendererPage = await page.context().newPage(); const rendererErrors = []; rendererPage.on('pageerror', error => rendererErrors.push(error.message)); await rendererPage.addInitScript(() => { const original = HTMLCanvasElement.prototype.getContext; HTMLCanvasElement.prototype.getContext = function (kind, ...args) { if (kind === 'webgl' || kind === 'webgl2' || kind === 'experimental-webgl') return null; return original.call(this, kind, ...args); }; }); await rendererPage.goto('/?e2e=1'); await expect(rendererPage.getByTestId('webgl-fallback')).toBeVisible(); if (await rendererPage.getByTestId('start-race').isVisible()) await rendererPage.getByTestId('start-race').click({ force: true }); await expect(rendererPage.getByTestId('webgl-fallback')).toBeVisible(); expect(await rendererPage.locator('canvas').count()).toBe(0); expect(rendererErrors).toEqual([]); await rendererPage.close(); });
